from django.shortcuts import render,HttpResponse
from django.core.files.storage import FileSystemStorage
# Create your views here.
import predictt

def index(request):
    return render(request,"index.html")

def checkleaf(request):
    if request.method == 'POST':
        #imgg = request.POST['image']
        # print(type(img))
        # print(img)
        #predicted_class,confidence_score=predictt.predict_class(img)
        #print(predicted_class)
        upload = request.FILES['image']
        print(type(upload))
        print(upload.name)
        fss = FileSystemStorage()
        file = fss.save(upload.name, upload)
        file_url = fss.url(file)
        img = r"F:\project-final-final\medic\media\{0}".format(upload.name)
        predicted_class,confidence_score=predictt.predict_class(img)
        print(predicted_class)


        
        new = "Aloe is a cactus-like plant that grows in hot, dry climates. It is cultivated in subtropical regions around the world, including the southern border areas of Texas, New Mexico, Arizona, and California.Historically, aloe has been used for skin conditions and was thought to improve baldness and promote wound healing.Aloe is used topically (applied to the skin) and orally. Topical use of aloe is promoted for acne, lichen planus (a very itchy rash on the skin or in the mouth), oral submucous fibrosis, burning mouth syndrome, burns, and radiation-induced skin toxicity. Oral use of aloe is promoted for weight loss, diabetes, hepatitis, and inflammatory bowel disease (a group of conditions caused by gut inflammation that includes Crohn’s disease and ulcerative colitis)."

        aloevera = "Aloe vera is a succulent plant species of the genus Aloe.It is widely distributed, and is considered an invasive species in many world regions. An evergreen perennial, it originates from the Arabian Peninsula, but grows wild in tropical, semi-tropical, and arid climates around the world. It is cultivated for commercial products, mainly as a topical treatment used over centuries. The species is attractive for decorative purposes, and succeeds indoors as a potted plant. The leaves of Aloe vera contain significant amounts of the polysaccharide gel acemannan which can be used for a wide range of medical purposes. The skin contains aloin which is toxic. Products made from Aloe vera usually only use the gel. There are many products containing Aloe vera's acemannan, including skin lotions, cosmetics, ointments and gels for minor burns and skin abrasions. Oral ingestion of Aloe vera extracts can be dangerous, because it causes reactions which are not fully understood yet. It is especially dangerous for pregnant women, some people have allergic reactions, even when only applied to the skin."
        neema = "Azadirachta indica, commonly known as neem, nimtree or Indian lilac, is a tree in the mahogany family Meliaceae. It is one of two species in the genus Azadirachta. It is native to the northeast of the Indian subcontinent and to Indochina, but is naturalized and grown around the world in tropical and subtropical areas. Its fruits and seeds are the source of neem oil. Neem  is a Hindustani noun derived from Sanskrit nimba.Neem is a fast-growing tree that can reach a height of 15–20 metres (49–66 ft), and rarely 35–40 m (115–131 ft). It is evergreen, shedding many of its leaves during the dry winter months. The branches are wide and spreading. The fairly dense crown is roundish and may reach a diameter of 20–25 m (66–82 ft). The opposite, pinnate leaves are 20–40 cm (8–16 in) long, with 20 to 30 medium to dark green leaflets about 3–8 cm long. The terminal leaflet often is missing. The petioles are short.White and fragrant flowers are arranged in more-or-less drooping axillary panicles which are up to 25 cm (10 in) long. The inflorescences, which branch up to the third degree, bear from 250 to 300 flowers. An individual flower is 5–6 mm  long and 8–11 mm  wide. Protandrous, bisexual flowers and male flowers exist on the same individual tree.The fruit is a smooth (glabrous), olive-like drupe which varies in shape from elongate oval to nearly roundish, and when ripe is 14–28 mm by 10–15 mm . The fruit skin (exocarp) is thin and the bitter-sweet pulp (mesocarp) is yellowish-white and very fibrous. The mesocarp is 3–5 mm  thick. The white, hard inner shell (endocarp) of the fruit encloses one, rarely two, or three, elongated seeds (kernels) having a brown seed coat."
        brahmia = "Bacopa monnieri is a perennial, creeping herb native to the wetlands of southern and Eastern India, Australia, Europe, Africa, Asia, and North and South America. It is known by the common names water hyssop,[1] waterhyssop, brahmi, thyme-leafed gratiola, herb of grace, and Indian pennywort. Bacopa monnieri is used in Ayurveda. In 2019, the US Food and Drug Administration (FDA) warned manufacturers of dietary supplement products containing Bacopa monnieri against making illegal and unproven claims that the herb can treat various diseases.Bacopa monnieri is a non-aromatic herb. The leaves of this plant are succulent, oblong, and 4–6 mm  thick. Leaves are oblanceolate and are arranged oppositely on the stem. The flowers are small, actinomorphic and white, with four to five petals. It can even grow in slightly brackish conditions. Propagation is often achieved through cuttings.Bacopa monnieri is used in Ayurvedic traditional medicine to improve memory and to treat various ailments. Reviews of preliminary research found that Bacopa monnieri may improve cognition, although the effect was measurable only after several weeks of use.In 2019, the FDA issued warning letters to manufacturers of dietary supplements containing Bacopa monnieri that advertised health claims for treating or preventing stomach disease, Alzheimer's disease, hypoglycemia, blood pressure, and anxiety were unproven and illegal. The FDA stated that Bacopa monnieri products have not been approved for these or any medical purposes."
        karpoora = "Cinnamomum camphora is a large and spreading tree, often growing 15-30 m tall. The rough bark is light brown or greyish-brown in colour, scaly or fissured, and has a strong odour (it is highly aromatic). Young branches are green or reddish-green in colour, rounded and hairless (glabrous).The leaves are alternately arranged, but sometimes densely clustered (pseudo-whorled), with leaf stalks (petioles) 15-40 mm long. These leaves (4.5-11 cm long and 2.4-6 cm wide) vary from oval (elliptic) to broadly egg-shaped in outline with broad end at base (broadly ovate) and have three distinct veins spreading from their bases. Their upper surfaces are bright green and glossy, while their undersides are paler green and duller in nature. They are hairless (glabrous) with entire margins that are often wavy (undulating), and have pointed tips (acute apices). The leaf buds are enclosed in distinctive overlapping scales when they are young. Oil glands and two small raised swellings (domatia) are evident on the undersides of the leaves, if they are observed with a hand lens. The flowers are small with six whitish, greenish-white or pale yellowish 'petals' (perianth lobes) 1.5-3 mm long. They also have 5-9 stamens. These flowers are borne in small branched clusters (about 7.5 cm long) at the tips of the branches (in terminal panicles).The fruit look like 'berries', but they are actually drupes containing a hard centre. These fruit are globular (8-10 mm across), glossy in appearance, and turn from green to black as they mature. They are attached to the stem by an enlarged, greenish-coloured, cone-shaped or cup-like structure (a conical or cupular receptacle) that is about 5 mm across"
        turmerica = "Turmericis a flowering plant, Curcuma longa of the ginger family, Zingiberaceae, the rhizomes of which are used in cooking. The plant is a perennial, rhizomatous, herbaceous plant native to the Indian subcontinent and Southeast Asia that requires temperatures between 20 and 30 °C (68 and 86 °F) and high annual rainfall to thrive. Plants are gathered each year for their rhizomes, some for propagation in the following season and some for consumption. The rhizomes are used fresh or boiled in water and dried, after which they are ground into a deep orange-yellow powder commonly used as a coloring and flavoring agent in many Asian cuisines, especially for curries, as well as for dyeing, characteristics imparted by the principal turmeric constituent, curcumin. Turmeric powder has a warm, bitter, black pepper-like flavor and earthy, mustard-like aroma. Curcumin, a bright yellow chemical produced by the turmeric plant, is approved as a food additive by the World Health Organization, European Parliament, and United States Food and Drug Administration.Although long used in Ayurvedic medicine, where it is also known as haridra, there is no high-quality clinical evidence that consuming turmeric or curcumin is effective for treating any disease."
        amlaa = "Emblica officinalis Gaertn. or Phyllanthus emblica Linn, commonly known as Indian gooseberry or amla, is arguably the most important medicinal plant in the Indian traditional system of medicine, the Ayurveda. Various parts of the plant are used to treat a range of diseases, but the most important is the fruit. The fruit is used either alone or in combination with other plants to treat many ailments such as common cold and fever; as a diuretic, laxative, liver tonic, refrigerant, stomachic, restorative, alterative, antipyretic, anti-inflammatory, hair tonic; to prevent peptic ulcer and dyspepsia, and as a digestive. Preclinical studies have shown that amla possesses antipyretic, analgesic, antitussive, antiatherogenic, adaptogenic, cardioprotective, gastroprotective, antianemia, antihypercholesterolemia, wound healing, antidiarrheal, antiatherosclerotic, hepatoprotective, nephroprotective, and neuroprotective properties. In addition, experimental studies have shown that amla and some of its phytochemicals such as gallic acid, ellagic acid, pyrogallol, some norsesquiterpenoids, corilagin, geraniin, elaeocarpusin, and prodelphinidins B1 and B2 also possess antineoplastic effects. Amla is also reported to possess radiomodulatory, chemomodulatory, chemopreventive effects, free radical scavenging, antioxidant, anti-inflammatory, antimutagenic and immunomodulatory activities, properties that are efficacious in the treatment and prevention of cancer. This review for the first time summarizes the results related to these properties and also emphasizes the aspects that warrant future research to establish its activity and utility as a cancer preventive and therapeutic drug in humans."
        pepperminta = "Peppermint (Mentha × piperita) is a hybrid species of mint, a cross between watermint and spearmint. Indigenous to Europe and the Middle East, the plant is now widely spread and cultivated in many regions of the world.[3] It is occasionally found in the wild with its parent species. Although the genus Mentha comprises more than 25 species, the one in most common use is peppermint. While Western peppermint is derived from Mentha × piperita, Chinese peppermint, or bohe, is derived from the fresh leaves of M. haplocalyx. M. × piperita and M. haplocalyx are both recognized as plant sources of menthol and menthone, and are among the oldest herbs used for both culinary and medicinal products.Peppermint typically occurs in moist habitats, including stream sides and drainage ditches. Being a hybrid, it is usually sterile, producing no seeds and reproducing only vegetatively, spreading by its runners. Outside of its native range, areas where peppermint was formerly grown for oil often have an abundance of feral plants, and it is considered invasive in Australia, the Galápagos Islands, New Zealand, and the United States in the Great Lakes region, noted since 1843."
        tulsia = "The predominant cause of global morbidity and mortality is lifestyle-related chronic diseases, many of which can be addressed through Ayurveda with its focus on healthy lifestyle practices and regular consumption of adaptogenic herbs. Of all the herbs used within Ayurveda, tulsi (Ocimum sanctum Linn) is preeminent, and scientific research is now confirming its beneficial effects. There is mounting evidence that tulsi can address physical, chemical, metabolic and psychological stress through a unique combination of pharmacological actions. Tulsi has been found to protect organs and tissues against chemical stress from industrial pollutants and heavy metals, and physical stress from prolonged physical exertion, ischemia, physical restraint and exposure to cold and excessive noise. Tulsi has also been shown to counter metabolic stress through normalization of blood glucose, blood pressure and lipid levels, and psychological stress through positive effects on memory and cognitive function and through its anxiolytic and anti-depressant properties. Tulsi's broad-spectrum antimicrobial activity, which includes activity against a range of human and animal pathogens, suggests it can be used as a hand sanitizer, mouthwash and water purifier as well as in animal rearing, wound healing, the preservation of food stuffs and herbal raw materials and traveler's health. Cultivation of tulsi plants has both spiritual and practical significance that connects the grower to the creative powers of nature, and organic cultivation offers solutions for food security, rural poverty, hunger, environmental degradation and climate change. The use of tulsi in daily rituals is a testament to Ayurvedic wisdom and provides an example of ancient knowledge offering solutions to modern problems."
        pipala = "Long pepper (Piper longum), sometimes called Indian long pepper or pippali, is a flowering vine in the family Piperaceae, cultivated for its fruit, which is usually dried and used as a spice and seasoning. Long pepper has a taste similar to, but hotter than, that of its close relative Piper nigrum – from which black, green and white pepper are obtained.The fruit of the pepper consists of many minuscule fruits – each about the size of a poppy seed – embedded in the surface of a flower spike that closely resembles a hazel tree catkin. Like Piper nigrum, the fruits contain the pungent compound piperine, which contributes to their pungency. Another species of long pepper, Piper retrofractum, is native to Java, Indonesia. The fruits of this plant are often confused with chili peppers, which belong to the genus Capsicum, originally from the Americas.Though often used in medieval times in spice mixes like 'strong powder', long pepper is today a very rare ingredient in European cuisines, but it can still be found in Indian and Nepalese vegetable pickles, some North African spice mixtures, and in Indonesian and Malaysian cooking. It is readily available at Indian grocery stores, where it is usually labeled pippali. Pippali is the main spice of Nihari, one of the national dishes of Pakistan and the Indian metropolis of Lucknow"
        ashvagandhaa = "Withania somnifera, known commonly as ashwagandha or winter cherry, is an evergreen shrub in the Solanaceae or nightshade family that grows in India, the Middle East, and parts of Africa. Several other species in the genus Withania are morphologically similar.The plant, particularly its root powder, has been used for centuries in traditional Indian medicine. Although used in herbalism and sold as a dietary supplement, there is insufficient scientific evidence that it is safe or effective for treating any health condition or disease.Withania somnifera is prone to several pests and diseases. Leaf spot disease caused by Alternaria alternata is the most prevalent disease, which occurs in a severe form in Punjab, Haryana, and Himachal Pradesh. A decline in the concentration of its secondary metabolites occurs by leaf spot disease. A treehopper feeds on the apical portions of the stem, making them rough and woody in appearance and brown in colour. citation needed. The carmine red spider mite (Tetranychus urticae) is the most prevalent pest of the plant in India. In recent years, this plant has been serving as a new reservoir host for an invasive mealybug species Phenacoccus solenopsis."

        plant = ['aloevera','neem','brahmi','karpoor','turmeric','amla','peppermint','tulsi','pipal','ashvagandha']

        done = plant[predicted_class]

        if predicted_class == 0:
            return render(request, 'index.html',{'name': aloevera , 'pltname': done })
        elif predicted_class == 1:
            return render(request, 'index.html',{'name': neema , 'pltname': done })
        elif predicted_class == 2:
            return render(request, 'index.html',{'name': brahmia , 'pltname': done })
        elif predicted_class == 3:
            return render(request, 'index.html',{'name': karpoora , 'pltname': done })
        elif predicted_class == 4:
            return render(request, 'index.html',{'name': turmerica , 'pltname': done })
        elif predicted_class == 5:
            return render(request, 'index.html',{'name': amlaa , 'pltname': done })
        elif predicted_class == 6:
            return render(request, 'index.html',{'name': pepperminta , 'pltname': done })
        elif predicted_class == 7:
            return render(request, 'index.html',{'name': tulsia , 'pltname': done })
        elif predicted_class == 8:
            return render(request, 'index.html',{'name': pipala , 'pltname': done })
        elif predicted_class == 9:
             return render(request, 'index.html',{'name': ashvagandhaa , 'pltname': done })
        else:
            return HttpResponse({'rob':'no result found'})
        # done = plant[predicted_class]
        # done1 = plant[predicted_class]
        # return render(request, 'index.html',{'name': done1 , 'pltname': done })
        #return render(request,"predictt/predictt.html")
